### ISSUE TITLE
RPC is not updated when HTML file is opened

### ISSUE THREAD

**Issue by dfireBird** [Mstrodl/elcord#24]
I recently started creating my own assets for elcord. While I'm doing that I noticed something when I open a HTML file (without having any form of configuration done for HTML files) the RPC is not showing that I'm editing that HTML file even after the delay (15 secs) and the RPC shows the buffer that I was last edited.

On the other hand, my friend, who has the web mode when edited a HTML file the RPC is showing that he is editing the HTML file.

**Comment by Zulu-Inuoe** [comment]
Unfortunately I can't replicate this - Maybe there's another mode enabled in Emacs that is somehow conflicting?

**Comment by dfireBird** [comment]
So it's a emacs problem?

P.S: I tried in a fresh emacs just installed elcord still not working.

**Comment by Zulu-Inuoe** [comment]
Okay, found out what's causing this - The reason is that the default HTML mode in Emacs has a mode name that is `((sgml-xml-mode "XHTML+" "HTML+") (:eval (mhtml--submode-lighter)))`
Which isn't a string and causes a bad message to get sent.

I'll add an entry for it in `elcord-mode-text-alist`, but also coerce the name to a string so that in the future this is captured - I didn't know `mode-name` could be anything other than a string

**Comment by Zulu-Inuoe** [comment]
Thanks!

**Comment by dfireBird** [comment]
Thanks for Fixing
